version: "3.2"

services:
  app:
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "8080:8080"
    tmpfs:
      - /tmp
    volumes:
      - .:/app/src
    environment:
      PYTHONDONTWRITEBYTECODE: 1
      
 
  postgresql:
    image: postgres:12.1
    ports:
      - "5432:5432"
    tmpfs:
      - /run
      - /var/run
      - /tmp
      - /var/lib/postgresql/data
    environment:
      - POSTGRES_INITDB_ARGS=--nosync --auth=trust
      - POSTGRES_USER=postgres
      - POSTGRES_DB=xfive_reco
    command: >
      postgres
        -c max_connections=50
        -c shared_buffers=2GB
        -c temp_buffers=256MB
        -c work_mem=128MB
        -c maintenance_work_mem=256MB
        -c effective_cache_size=4GB
        -c autovacuum=off
        -c wal_buffers=32MB
        -c max_wal_size=2GB
        -c checkpoint_timeout=60min
        -c checkpoint_completion_target=0.9
        -c max_locks_per_transaction=1024
        -c fsync=off
        -c synchronous_commit=off
        -c full_page_writes=off
        -c log_statement=none
        -c logging_collector=off
        -c log_min_duration_statement=-1
        -c log_min_error_statement=panic
        